#!/bin/bash
# Copyright PCLP Team, 2025

sudo apt-get update

sudo apt-get install                        \
    gcc                                     \
    python3 python3-pip                     \
    perl                                    \
    make gdb valgrind

# Starting with pip 23.0, installing packages outside a venv is restricted by default.
# This change was introduced to prevent accidental system-wide package installations.
# See: https://pip.pypa.io/en/stable/news/#v23-0-1
# We need to set PIP_BREAK_SYSTEM_PACKAGES=1 to allow the checker's dependencies to be installed.
export PIP_BREAK_SYSTEM_PACKAGES=1
pip3 install --user recordclass
